import directly_differentiable_curves_geometric_order_lemma_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace directly_differentiable_curves_geometric_order_lemma_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end directly_differentiable_curves_geometric_order_lemma_canonical_lane_mathlib
end HautevilleHouse
